README.md
lib.c
tests/custom/03_bugs/19_truncated_format_string
types.c
types.h

- Properly handle truncated format strings
- Support pretty printing JSON

String format improvements

---

README.md
lib.c

lib: implement assert()

---

compiler.h
vm.c
vm.h

vm, compiler: get rid of unused struct members

---

lib/fs.c

- The chmod() function expects a path string as first and an integer mode
value as second argument.
- The chown() function takes a path string as first argument, and either
a string, an integer or null as second user and third group argument
respectively.
If either user or group are given as string, they're resolved to an
uid/gid using getpwnam()/getgrnam() internally. If either lookup fails,
the ownership change is not performed.
If either user or group are null or -1, they're left unchanged.
- The rename() function takes two path strings, the old path being the
first argument and the new path the second one.
- The glob() function takes an arbitrary number of glob patterns and
resolves matching files for each one. In case of multiple patterns,
no efforts are made to remove duplicates or …

fs: implement chmod(), chown(), rename() and glob() functions

---

README.md
lib.c

The new functions allow encoding and decoding base64 values respectively.

lib: implement b64enc() and b64dec() functions

---

lib/fs.c

Implement support for opening existing file descriptors as well as acquiring
the descriptor number from open process and file handles.

fs: implement fdopen(), file.fileno() and proc.fileno()

---

lib.c

Instead of extracting and forwarding recognized conversion directives
from the user supplied format string, properly parse the format string
into its components and reassemble a canonical representation of the
conversion directive internally before handing it to the libc's sprintf()
implementation.
Also take care of selecting the proper conversion specifiers for signed
and unsigned 64bit integer values to fix broken `%d`, `%i`, `%u`, `%o`,
`%x` and `%X` formats on 32bit systems.
While reworking the format logic, also slightly improve `%s` argument
handling by not duplicate the given value if it already is a string,
which reduces the amount of required heap memory.
Ref: https://bugs.openwrt.org/index.php?do=details&task_id=4234
Ref: …

lib: rework format string handling

---

lib/struct.c

Implement a new `*` format which acts like `s` on unpack but accepts
input records which are shorter than the specified length, e.g. the
following call will yield "abc" while an equivalent "10s" format would
fail:
unpack("2*", "abc")  // [ "ab" ]
unpack("10*", "abc") // [ "abc" ]
unpack("10s", "abc") // null
The `*` format is primarily useful to extract the remainder of a variable
length record without having to encode the specific length of the record
directly into the format string.
When packing records, the `*` format takes at most as many bytes as
specified in the format string repeat count. If the input string is
shorter than the given repeat count, only as many bytes as present in
the input string are taken. A bare `*` without any repeat count will take
all bytes from the given …

struct: implement `*` format, fix invalid memory accesses

---

lib/uloop.c

Tasks are similar to processes but instead of executing a new process, an
ucode function is invoked instead, running independently of the main
process.
Example usage:
```javascript
uloop.init();
let t = uloop.task(
// program function
function(pipe) {
let input = pipe.receive();
pipe.send({ got_input: input });
return { result: true };
},
// parent recv function, invoked when task function calls pipe.send()
function(res) {
printf("Received output message: %.J\n", res);
},
// parent send function, invoked when task function calls pipe.receive()
function() {
let input = { test: "Example" };
printf("Sending input message: %.J\n", input);
return input;
}
);
uloop.run();
```

uloop: add support for tasks

---

lib/fs.c

The `fs.readfile()` and `fs.writefile()` functions allow efficient reading
and writing of whole files, reducing the required boilerplace code compared
to using the `open()`/`read()`/`write()`/`close()` API.
- `fs.readfile()` takes two arguments; the path to open and an optional
limit value. If limit is omitted, `null` or negative, the entire file
contents are read, otherwise the specified amount of bytes. Returns the
read file contents as string or `null` on error.
- `fs.writefile()` takes three arguments; the path to open/create, the
contents to write and an optional limit value. If limit is omitted, the
entire content is written, otherwise just the specified amount of bytes.
Non-string content arguments are internally converted to strings, `null`
is treated as empty string. Returns the …

fs: implement `fs.readfile()` and `fs.writefile()`

---

lib/rtnl.c

For route netlink request messages having a header struct, uc_nl_request()
invokes nlmsg_reserve() to reserve room for the struct data but the
nlmsg_reserve() function only zeroes additional alignment bytes, not the
actual reserved buffer space.
Extend the existing logic to explicitly zero out the reserved header space
in order to avoid sending uninitialized struct member values to the kernel.

rtnl: zero request message headers

---

lib/struct.c

Extend the `unpack()` function to take an optional, second offset parameter
which is useful to skip an initial portion of the input data without having
to encode pad bytes into the format string.

struct: add optional offset argument to `unpack()`

---

lib/uloop.c

Instead of silently continuing, end the uloop when encountering exceptions
in ucode callbacks to let those exceptions propagate to the host program.

uloop: end uloop on exceptions in managed code

---

lib/ubus.c

Instead of silently continuing, end the uloop when encountering exceptions
in ucode callbacks to let those exceptions propagate to the host program.

ubus: end uloop on exceptions in managed code

---

include/ucode/types.h
include/ucode/vm.h
lib.c
main.c
tests/cram/test_basic.t
tests/custom/03_stdlib/60_gc
types.c
vm.c

This PR introduces the ability to activate periodic garbage collection of cyclic objects.

Implement periodic GC

---

lib/nl80211.c

Signed-off-by: John Crispin <john@phrozen.org>

nl80211: add support for NL80211_ATTR_MPATH_INFO

---

lib/nl80211.c
lib/rtnl.c

Add missing ucv_get calls in rtnl/nl80211

Fix reference count issues

---

lib/uci.c

A uci commit operation may invalidate the package pointer, leading to an infinite loop while iterating the packages to commit.
Refactor the code to first build a string list of configurations, then iterating it in order to avoid the iterator invalidation.
While we're at it, also allow restricting save and revert operations to single configs, which was rejected as invalid before.
Fixes: #146

uci: fix ctx.commit() without arguments

---

lib/struct.c
lib/ubus.c
main.c
tests/cram/test_basic.t
types.c
vm.c

Fixes for minor things that I noticed during review

A few minor fixes/improvements to ucode

---

README.md

Build fails without pkg-config.

README.md: fix debian dependencies

---

lib/fs.c

Add missing function documentation and return value annotations.

fs: complete function documentation coverage

---

lib/debug.c
lib/struct.c

Add documentation coverage for the `struct` module.

Documentation improvements

---

lib/ubus.c

Allows other C code to gain access to the ubus context without having to know the layout of the other fields.
Also reduce the amount of unnecessary pointer indirection

ubus: make ubus_context first in uc_ubus_connection_t

---

lib/socket.c

Add the required infrastructure to support Linux AF_PACKET sockets:
- Add related constants
- Add struct definitions for SOL_PACKET socket options
- Add AF_PACKET family support to sockaddr routines

socket: add AF_PACKET socket type support

---

lib.c

Add to docs for `int`, `map` and `filter`.  Fix a few stray typos in other function's docs.
Most notable are examples in `map`, which describe how naive use of `int` as the mapping function can give very non-intuitive results.
Fixes #205.
Edit: Forgot to mention that I didn't test it, I couldn't (ha, too lazy to) figure out how to generate the doc files from the code, so...

core-lib: improved documentation

---

lib.c

Utilize the newly introduced sort functions to eliminate the global sort context usage. This change was originally part of PR #242 but got dropped during refactoring.

lib: utilize `ucv_array_sort_r()` and `ucv_object_sort_r()`

---

lib/uci.c

Use the VM registry to store the last uci error code and lookup the uci cursor resource type at resource creation time instead of caching it in a global variable.

uci: eliminate usage of global variables

---

main.c

Fill it with the command line provided path to the source file

main: add global ARGV0 variable

---

lib/uci.c

Introduce two new functions list_append(conf, section, option, value) and list_remove(conf, section, option, value) which add and remove values from uci list options, respectively.
Fixes: #279

uci: implement cursor.list_append() and cursor.list_remove()

---

lib/socket.c

This socket option needs to be set before the bind call(). Since it's very commonly used, adding a parameter for it makes sense.

socket: add reuseaddr argument for socket.listen()

---

lib/ubus.c

Stop using the registry for references passed by the user

ubus: use ucv_resource_create_ex and embedded references

---

lib/resolv.c

Refactor `parse_nsaddr()` to not modify the given address string in-place but to use a scratch buffer for extracting the IP address portion of the strings.
Also add complete documentation coverage for the module.
Fixes: #313

resolv: add documentation and fix clobbering ns strings

---

include/ucode/vm.h
lib/ubus.c
lib/uloop.c
vm.c

Add exported vm.c function for generating an exception ucode value.
Add a function to ubus and uloop for setting a custom exception handler function

Exception handling improvements

---

lib/socket.c

- socket.pair() for establishing a pair of connected sockets
- socket.open() for opening a socket from a file descriptor

socket module enhancements
