jow-/ucode

compiler.c, tests/custom/00_syntax/22_strict_mode, types.h, vm.c
Support per-file and per-function `"use strict";` statement to opt into
strict variable handling from ucode source code.
=> syntax: implement support for 'use strict' pragma

README.md, lib.c, types.h, vm.c
The new render() function shares the same semantics with include() but captures
the output of the processed ucode in a string and returns it.
=> Introduce render() function

CMakeLists.txt, README.md, compiler.c, lexer.c, lexer.h, lib.c, value.c, value.h, vm.c, vm.h
- Provide a new function `wildcard()` which wraps `fnmatch(3)` to allow matching strings against simplified glob patterns
- Reimplement `delete` as proper unary operator
- Introduce build option to disable deprecated syntax elements
=> Various additions

README.md, compiler.c, compiler.h, lexer.c, lexer.h
Introduce support for declaring constant variables through the `const`
keyword. Variables declared with `const` follow the same scoping rules
as `let` declared ones.
In contrast to normal variables, `const` ones may not be assigned to
after their declaration. Any attempt to do so will result in a syntax
error during compilation.
=> syntax: introduce `const` support

include/ucode/types.h, include/ucode/vm.h, lib/ubus.c, types.c, vm.c
Introduce a new ubus.defer() method which initiates asynchroneous requests
and invokes the completion callback passed as 4th argument once the reply
is received.
This allows multiplexing mutliple ubus requests with the same ucode VM
context / the same uloop event loop.
In case the ucode context is not running under an active uloop, the ubus
module will spawn uloop itself once the first asynchroneous request is
launched and terminate the loop once all pending requests finished.
=> ubus: add support for async requests

CMakeLists.txt, compiler.c, include/ucode/types.h, include/ucode/vallist.h, lexer.c, lib.c, lib/math.c, lib/nl80211.c, lib/rtnl.c, tests/custom/00_syntax/10_numeric_literals, tests/custom/01_arithmetic/02_modulo, tests/custom/01_arithmetic/03_bitwise, tests/custom/01_arithmetic/05_overflow, types.c, vallist.c, vm.c
- Parse integer literals as unsigned numeric values in order to be able
to represent the entire unsigned 64bit value range
- Stop parsing minus-prefixed integer literals as negative numbers but
treat them as separate minus operator followed by a positive integer
instead
- Only store unsigned numeric constants in bytecode
- Rework numeric comparison logic to be able to handle full 64bit
unsigned integers
- If possible, yield unsigned 64 bit results for additions
- Simplify numeric value conversion API
- Compile code with -fwrapv for defined signed overflow semantics
=> treewide: rework numeric value handling

include/ucode/vallist.h, lib/struct.c, vallist.c, vm.c
Import the binary64 double packing routines from the struct module and
use them to store numeric double values in a platform agnostic big
endian format.
=> Platform neutral doubles

README.md, lib.c
The uniq() function allows extracting all unique values from a given input
array in an efficient manner. It is roughly equivalent to the following
ucode idiom:
let seen = {}
let unique = filter(array, item => !seen[item]++);
In contrast to the code above, `uniq()` does not rely on implicit
stringification of item values but performs strict equality tests internally.
If equivalence of stringified results is desired, the following code can
be used:
let unique = uniq(map(array, item => "" + item));
=> lib: implement uniq() function

CMakeLists.txt, chunk.c, compiler.c, include/ucode/chunk.h, include/ucode/compiler.h, include/ucode/program.h, include/ucode/source.h, include/ucode/types.h, include/ucode/util.h, include/ucode/vallist.h, lexer.c, lib.c, main.c, program.c, source.c, tests/cram/test_basic.t, types.c, vallist.c, vm.c
This PR adds a series of commits to support bytecode precompilation in ucode:
- **types: add initial infrastructure for function serialization**
Introduces a new logical "program" object which holds the list of compiled functions,
changes handling of function values in constant lists; instead of storing the pointer values
directly, it stores an index into the program's function list
- **compiler, vm: use a program wide constant list**
So far, each compiled ucode function maintained its own constant data list which leads
to considerable overhead if a program consists of many functions. This commit moves
the per-function constant data into one global per-program constant data area, avoiding
duplication of large constant values
- **source: refactor source file handling**
Introduces support …
=> Introduce ucode precompilation support

compiler.c, include/ucode/program.h, include/ucode/source.h, include/ucode/types.h, lib.c, main.c, program.c, source.c
Fix two issues encountered while testing precompilation on complex programs:
- Within `uc_require_ucode()`, the compiled program function was not released after invoking it, leading to a leak of the function itself and all associated values
- When executing precompiled bytecode files, the effective path of the file being executed by the VM was not tracked, instead the source buffer `->filename` member referred to the path of the original source file or - in case of stripped debug information - nowhere, causing `uc_include()` and `uc_sourcepath()` to fail
These changes address these issues and modify the bytecode loading API while we're touching it.
=> Bytecode fixes

compiler.c, examples/exception-handler.c, examples/execute-file.c, examples/execute-string.c, examples/native-function.c, examples/state-reset.c, examples/state-reuse.c, include/ucode/compiler.h, include/ucode/program.h, include/ucode/source.h, include/ucode/types.h, include/ucode/vallist.h, include/ucode/vm.h, lib.c, main.c, program.c, source.c, types.c, vallist.c, vm.c
- Instead of treating individual program functions as managed ucode types,
demote uc_function_t values to pointers into a uc_program_t entity
- Promote uc_program_t to a managed type
- Let uc_closure_t claim references to the owning program of the enclosed
uc_function_t
- Redefine public APIs uc_compile() and uc_vm_execute() APIs to return and
expect an uc_program_t object respectively
- Remove vallist indirection for function loading and let the compiler
emit the function id directly when producing function construction code
=> treewide: rework function memory model

lib/ubus.c, lib/uloop.c
Extend the ubus binding to cover ubus object publishing, notifications on
objects, as well as subscriber APIs.
Instantiating ubus objects:
obj = conn.publish("objname", {
methodname: {
args: { ...argspec... },
call: function(request) { ...method handler... }
},
...
}, function() { ...subscription status change handler... });
obj.notify(...);
obj.remove();
Emitting notifications:
obj.notify("notificationtype", { ...notification data... },
function(type, data) { ...data callback... },
function(idx, ret) { ...status callback... },
function() { ...completion callback... },
100 /* timeout */
);
Instantiating subscribers:
sub = conn.subscriber(
function(notify) { ...notification handler... },
function(id) { ...object gone handler... }
);
sub.subscribe("objname");
sub.unsubscribe("objname"); …
=> ubus: add object publishing, notify and subscribe support

tests/custom/04_bugs/33_vm_computed_prop_decl_crash, vm.c
When executing an object literal declaration using non-string computed
property name values, the VM crashed caused by an attempt to use a NULL
pointer (result of ucv_string_get() on a non-string value) as hash table
key.
Fix this issue by using the `ucv_key_set()` infrastructure which deals
with the implicit stringification of non-string key values.
=> vm: fix crash on object literals with non-string computed properties

lib.c
The current `uc_render()` implementation uses a `fseek()` call on the
`open_memstream()` provided `FILE *` stream to reserve headroom for the
`uc_string_t` header. The `fseek()` call alone does not guarantee that
the underlying buffer length is updated on all libc implementations though.
This may lead to an integer underflow later on when the `uc_string_t`
header length is substracted from the buffer length after invoking a
template that did not produce any output write operations. In such a
case, a very large value is assigned to `ustr->length` leading to
uninitialized or out-of-bounds memory accesses later on.
Solve this issue by writing the header structure as data using `fwrite()`
which should yield the expected behaviour on all libc environments.
Signed-off-by: Jo-Philipp Wich …
=> lib: fix potential integer underflow on empty render output

lib.c, main.c, tests/cram/test_basic.t, tests/custom/02_runtime/07_raw_template_mode_switching, tests/custom/03_stdlib/29_require, tests/custom/03_stdlib/35_include, tests/custom/run_tests.sh
- Change command line flags to be align better with those of other
interpreters and with the gcc compiler, e.g. `-D` and `-U` to
define and undefine globals, `-e` to execute script expression etc.
- Pass only excess CLI arguments as `ARGV` to scripts, e.g.
`ucode -e 'print("Hello world")' -- -x -y` would pass only
`[ "-x", "-y" ]` as ARGV contents
- Default to raw mode and introduce flag to enable template mode
-  Adjust require(), render() and include() raw mode semantics,
let `require()` always evaluate the executed code in raw mode,
let `render()` always evaluate the executed code in template mode,
let `include()` inherit the raw mode semantics of the calling scope
=> main: rework CLI frontend

lib.c, tests/custom/03_stdlib/27_sprintf, tests/custom/03_stdlib/28_printf
This allows writing format patterns that utilize the arguments in a different order than passed to the function.
=> lib: add argument position support (`%m$`) to `sprintf()` and `printf()`

include/ucode/lib.h, lib.c
Provide a new API function `uc_stdlib_function()` which allows to fetch
the C implementation of the given named standard library function.
This is useful for loadable modules or applications that embed ucode which
want to reuse core functions such as `sprintf()`.
=> lib: provide API function to obtain stdlib function implementations

README.md, lib.c, tests/custom/03_stdlib/51_localtime, tests/custom/03_stdlib/52_gmtime, tests/custom/03_stdlib/53_timelocal, tests/custom/03_stdlib/54_timegm, tests/custom/03_stdlib/55_clock
Add five new functions to deal with date calculation and timing:
- localtime(), gmtime() - return a broken down calendar date and time
specification from the given epoch (or now, if absent) in local and
UTC time respectively
- timelocal(), timegm() - the inverse operation for the former functions,
taking a date and time specification (interpreted as local or UTC time
respectively) and turning it into an epoch value
- clock() - return the second and nanosecond values of the system clock,
useful for time/performance measurements
=> lib: add date and time related functions

lib/fs.c, tests/custom/04_bugs/34_dirname_off_by_one
Make sure fs.dirname() doesn't truncate the last character of the
returned path. Previously ucv_string_new_length was called with a
length which no longer included the last character (which had just
been tested not to be a '/' or '.' and hence broke the loop at that
point).
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
=> fs: fix off-by-one in fs.dirname() function

include/ucode/compiler.h, include/ucode/util.h, include/ucode/vallist.h, json-c-compat.h, lib.c, main.c, types.c
Do not expose the json-c compat functions in ucode's public headers to
avoid clashes when building on systems with modern json-c.
Also remove some explicit json-c/json-c.h includes in places where it is
not needed.
=> treewide: move json-c compat shims into internal header file

tests/custom/04_bugs/36_vm_nested_call_return, vm.c
When a managed function is indirectly invoked during bytecode execution,
e.g. when calling the tostring() method of an object prototype during
string concatenation, the invoked function must stop executing bytecode
upon return to hand control back to caller.
Extend `uc_vm_execute_chunk()` to track the amount of nested function
calls it performs and hand back control to the caller once the toplevel
callframe returns. Also bubble unhandled exceptions only as far as up
to the original caller.
=> vm: stop executing bytecode on return of nested calls

.github/workflows/openwrt-ci-master.yml, .github/workflows/openwrt-ci-pull-request.yml
With the proliferation of test cases, CI runs tend to become rather long
since we run all tests under valgrind using multiple gcc and Clang
versions each.
In order to speedup the jobs, we tests pull requests under the most
recent Clang versions and run all tests when the code hits the master
branch.
Closes #66
Signed-off-by: Petr Štetiar <ynezz@true.cz>
=> ci: make jobs faster during pull request testing

include/ucode/vallist.h, lexer.c, lib.c, tests/custom/00_syntax/10_numeric_literals, tests/custom/03_stdlib/08_int, tests/custom/04_bugs/29_empty_string_as_number, vallist.c
-  syntax: adjust number literal parsing and string to number conversion
- Recognize new number literal prefixes `0o` and `0O` for octal as well
as `0b` and `0B` for binary number literals
- Treat number literals with leading zeros as octal while parsing but
as decimal ones on implicit number conversions, means `012` will yield
`10` while `+"012"` or `"012" + 0` will yield `12`
-  lib: refactor `uc_int()`
For string cases, turn `int()` into a thin `strtoll()` wrapper which
attempts to parse the initial portion of the string as a decimal integer
literal, optionally preceded by white space and a sign character.
Also introduce an optional `base` argument for string cases while we're
at it and adjust the existing stdlib test case accordingly.
The function now behaves mostly the same as …
=> Number literals

lib/struct.c
When packing a format such as `!6C*`, the `*` format was not included into
the result buffer due to improper tracking of the function argument offset.
Solve this issue by taking field repetitions into account when tracking
the argument offset while calculating the size of dynamic arguments.
=> struct: fix packing `*` format after other repeated formats

lib/rtnl.c
Some nested RTAs such as IFLA_INET_CONF do not contain actual sub-RTAs but
just an array of integers. Avoid calling a no-op `nla_parse()` for such
attributes to suppress the non-harmful leftover bytes warning emitted by
libnl.
=> rtnl: avoid stray "netlink: %d bytes leftover after parsing attributes."

lib/rtnl.c
The nl_recvmsgs() logic in uc_nl_request() incorrectly stopped reading
the socket before the netlink ACK message was handled for non-multipart
replies.
This caused subsequent requests to incorrectly receive the ACK of the
previous request, leading to a failure to receive the actual reply.
Fix this issue by continue reading the socket until either the finish
callback for multipart (dump) messages or the ack callback for non-
multipart messages was received.
This fix is basically the same as the one applied to the nl80211 module
in 54ef6c0 ("nl80211: fix premature netlink reply receive abort").
=> rtnl: fix premature netlink reply receive abort

lib/rtnl.c
Some link types, such as veth, yield an IFLA_LINKINFO nla without an
embedded IFLA_INFO_DATA / INFLA_INFO_SLAVE_DATA nla which causes the
nla converter to dereference a NULL nla pointer.
Properly deal with such cases and check for the existence of the
child nla before attempting to parse it.
=> rtnl: fix segmentation fault on parsing linkinfo RTA without data

lib/nl80211.c
Report the noise value as signed integer to calling ucode.
Reported-by: John Crispin <john@phrozen.org>
=> nl80211: fix NL80211_SURVEY_INFO_NOISE datatype

lib/rtnl.c
So far the NETLINK_GET_STRICT_CHK socket flag was only set on the implicit
socket creation performed during the first request and ignored for
subsequent ones which made it impossible to perform only some requests
with enabled strict checking.
Modify the logic to check the flag state for every request and change
it if needed. This allows performing both strict and non-strict requests
over the same connection.
=> rtnl: update NETLINK_GET_STRICT_CHK socket flag with every request

lib/rtnl.c
Decode IFLA_STATS64 attribute and make contained counters available to ucode.
=> rtnl: expose IFLA_STATS64 contents

lib/rtnl.c
Some pecularities in the encoding of the IFLA_AF_SPEC attribute make it
unsuitable for table driven parsing/generation.
To solve this issue, introduce specific datatype handling for IFLA_AF_SPEC
and parse/generate the RTA depending on the address family of the containing
netlink message.
=> rtnl: fix parsing/creation of IFLA_AF_SPEC RTA for the AF_BRIDGE family

lexer.c, tests/custom/04_bugs/40_lexer_bug_on_lstrip_off
When a template was parsed with global block left stripping disabled, then
any text preceding an expression or statement block start tag was incorrectly
prepended to the first token value of the block, leading to syntax errors in
the compiler.
=> lexer: fix parsing with disabled block left stripping

compiler.c, include/ucode/program.h, include/ucode/types.h, program.c, tests/custom/04_modules/06_export_errors, tests/custom/04_modules/07_import_default, tests/custom/04_modules/08_import_list, tests/custom/04_modules/12_import_immutability, tests/custom/04_modules/14_circular_imports, tests/custom/04_modules/15_complex_imports, vm.c
This PR introduces a series of fixes for the compilation of import and export statements.
- Fixes segmentation fault on loading and executing module constructors containing import upvals
- Fixes allocating export registry slots in the compiler
- Stricter compilation rules for modules
- Fixed relative module path resolving
- Improved error message formatting
=> Module import export fixes

compiler.c, include/ucode/lib.h, include/ucode/types.h, include/ucode/vm.h, lib.c, main.c, tests/cram/test_basic.t, tests/custom/04_modules/06_export_errors, vm.c
Major changes:
**lib: internally expose new uc_require_library() helper**
Break out the core logic of the uc_require() stl function into a new
uc_require_library() helper function and make it available for usage
outside of lib.c. Also add a new boolean parameter to the helper function
which allows restricting runtime require operations of modules to dynamic
libraries only.
**vm: introduce new I_DYNLOAD opcode**
The I_DYNLOAD opcode is basically a bytecode level instruction for
uc_require() with semantics similar to I_IMPORT. It allows loading
a dynamic extension library at runtime and treating values from the
resulting module context object like exports from a compile time source
module.
For example the statement `import { readfile, writefile } from "fs"`
would import the readfile() and …
=> Add import statement support for dynamic extensions

lib.c
Instead of supporting only up to 10 potential regular expression captures,
infer the amount of required captures directly from the compiled regexp
structure and allocate the match range array dynamically.
=> lib: remove fixed capture group limit in match() and regex replace()

lib/fs.c
Rework the `fs.open()` implementation to accept an optional third file
permission argument which is applied to newly created files.
=> fs: add optional third permission argument to fs.open()

compiler.c, lexer.c, main.c, tests/cram/test_basic.t, tests/custom/00_syntax/21_regex_literals, tests/custom/99_bugs/41_compiler_invalid_return_opcode, types.c
1. main: implement print mode
Introduce a new `-p` flag which works like `-e` but prints the final
expression result.
---
2. compiler: optimize function return opcode generation
Track last emitted statement type in compiled code and only generate final
`return null` opcodes if there is no preceeding `return` statement.
Also use this statement tracking to avoid emitting invalid return opcodes
for arrow function bodies with trailing empty statements.
---
3. lexer: improve regex literal handling
- Do not treat slashes within bracket expressions as delimitters
- Do not escape slashes when stringifying regex sources
=> Various improvements

README.md, lib.c, tests/custom/03_stdlib/64_slice
Implement a new function `slice()` to complement the existing `splice()` function and model it's semantics after the ES6 `Array.slice()` version.
Fixes: #106
=> lib: implement slice() function

lexer.c, tests/custom/00_syntax/21_regex_literals
- Ensure that regexp extension escapes are consistently handled; substitute `\d`, `\D`, `\s`, `\S`, `\w` and `\W` with `[[:digit:]]`, `[^[:digit:]]`, `[[:space:]]`, `[^[:space:]]`, `[[:alnum:]_]` and `[^[:alnum:]_]` character classes respectively since not all POSIX regexp implementations implement all of those extensions
- Preserve `\b`, `\B`, `\<` and `\>` boundary matches
Fixes: a45f2a3 ("lexer: improve regex literal handling")
=> lexer: fixes for regex literal parsing

lib/fs.c
Use `getline()` instead of a custom `fgets()` wrapper logic to perform line wise reads from open file handles. This is required to properly deal with lines containing embedded null bytes.
=> fs: use `getline()` for line wise read operations

lib/fs.c
When `fd.read()` is invoked with a single-character string argument, invoke `getdelim()` internally to read the input until the give character or EOF. This is useful for reading character delimited input data.
For example `fd.read('\n')` will read any data up to the first newline (or EOF) while `fd.read('\0x00')` will read until the first null byte.
=> fs: expose `getdelim()` functionality through `fd.read()`

README.md
This PR adds cmake to the install depends.
If cmake is not installed `dpkg-buildpackage -b -us -uc` fails with the following message:
```bash
Can't exec "cmake": No such file or directory at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 522.
```
=> add cmake to install requires for debian

compiler.c, tests/custom/00_syntax/19_arrow_functions
Follow ES6 semantics and ensure that arrow functions with a block body don't implicitly return the value of the last executed statement.
=> compiler: ensure that arrow functions with block bodies return no value

lib/uci.c
Functions that use `uci_lookup_ptr()` internally, such as `ctx.get()`, `ctx.set()` or `ctx.delete()`, implicitly load the given configuration name while the higher level functions `ctx.foreach()` or `ctx.get_first()` do not.
This behaviour violates the principle of least surprise and might lead to non-deterministic program behavior as the outcome of these functions depends on prior uci operations performed on the cursor.
Fix this issue by invoking `uci_load()` internally in case the given uci package name cannot be found in the cursor's package cache.
=> uci: auto-load package in `ctx.foreach()` and `ctx.get_first()`

lib.c
Only raise a trailing garbage error if the given JSON source string is followed by a non white space character.
=> lib: uc_json(): accept trailing whitespace when parsing strings

lib/uloop.c
Ensure that the main process uloop is terminated within task child processes. Before this fix, using uloop in a task function would trigger invalid memory accesses in the parent process by notifying non-existing fd slots in the parent through the inherited shared epoll descriptor.
=> uloop: terminate parent uloop in task child processes

lib/math.c
Add a new `isnan()` convenience function to the math library which can be used to test if a given value is a NaN double.
The same test can be realized without the math library by using a function similar to the following one:
```javascript
function isNaN(x) {
return x != x;
}
```
=> math: add isnan() function

compiler.c, tests/custom/00_syntax/25_and_or_assignment
The compiler emitted incorrect bytecode for logical assignment operations on property expressions. The generated instructions left the stack in an unclean state when the assignment condition was not fulfilled, causing a stack layout mismatch between compiler and vm, leading to undefined variable accesses and other non-deterministic behavior.
Solve this issue by rewriting the bytecode generation to yield an instruction sequence that does not leave garbage on the stack.
The implementation is not optimal yet, as an expression in the form `obj.prop ||= val` will load `obj.prop` twice. This is acceptable for now as the load operation has no side effect, but should be solved in a better way by introducing new instructions that allow for swapping stack slots, allowing the vm to operate on a copy …
=> compiler: fix bytecode for logical assignments of properties

include/ucode/lib.h, include/ucode/types.h, types.c
Can be used to get rid of a layer of pointer indirection in resource type handlers.
=> include: add uc_fn_thisval()

lib/fs.c, tests/custom/03_stdlib/40_proto
Expose the `isatty(3)` libc function in the fs module to allow checking whether a file descriptor refers to a terminal.
Signed-off-by: Petr Štetiar <ynezz@true.cz>
=> fs: add `isatty()` function

lib/nl80211.c
This is the last attribute, adapt .nattr to include it so it gets parsed.
Signed-off-by: Andre Heider <a.heider@gmail.com>
=> nl80211: fix NL80211_ATTR_SURVEY_INFO

lib/rtnl.c
Fixes maintaining the listener array
=> rtnl: add missing uc_vm_registry_set call

.github/workflows/debian.yml, .github/workflows/macos.yml, .github/workflows/openwrt-ci-master.yml, .github/workflows/openwrt-ci-pull-request.yml
SDK containers hosted under `openwrtorg` Docker organization were deprecated so lets use fixed action version v0.0.2 which uses new `openwrt` organization.
References: https://lists.openwrt.org/pipermail/openwrt-devel/2023-March/040728.html
* Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> ci: unbreak failing builds by using fixed gh-actions-openwrt-ci-sdk

program.c
Fix Coverty Scan CID 1521109 reporting a memory leak for path not freed on read_size_t fail.
=> program: fix memory leak in read_sourceinfo

README.md, include/ucode/types.h, lib.c, tests/custom/03_stdlib/16_sort, types.c
Extend `uc_sort()` to utilize `ucv_object_sort()` in order to support
reordering object keys.
=> lib: support object ordering in `uc_sort()`

.github/workflows/macos.yml, .github/workflows/openwrt-ci-master.yml, .github/workflows/openwrt-ci-pull-request.yml, .gitignore, openwrt/ucode/Makefile
Utilize the official openwrt/gh-action-sdk CI actions to test-build OpenWrt packages.
=> ci: switch to official openwrt/gh-action-sdk

lexer.c, source.c, tests/custom/03_stdlib/29_require, tests/custom/03_stdlib/35_include, tests/custom/03_stdlib/36_render, tests/custom/03_stdlib/62_loadfile, tests/custom/99_bugs/14_incomplete_expression_at_eof, tests/custom/99_bugs/25_lexer_shifted_offsets
This PR fixes a number of minor issues with the source offset tracking leading to incorrect line/byte positions when decoding debug information to obtain the declaration spot of variables or similar.
- When skipping the interpreter line, don't count it's newline twice
- Fix reporting byte offsets beyond the end of line
-  Don't count EOF token as newline
=> Fixes for source offset tracking

lib/fs.c
Use `fseeko()` and `ftello()` instead of `fseek()` and `ftell()` respectively in order to be able to deal with large file offsets.
=> fs: use `fseeko()` and `ftello()`

include/ucode/types.h, include/ucode/vm.h, lib.c, lib/uloop.c, main.c, tests/custom/03_stdlib/60_gc, types.c, vm.c
This PR introduces the infrastructure for handling UNIX signals inside ucode.
=> Introduce signal handling

tests/custom/99_bugs/42_types_binary_string_comparison, types.c
The existing `ucv_compare()` implementation utilized `strcmp()` to compare two ucode string values, which may lead to incorrect results for strings containing null bytes as the comparison prematurely aborts when encountering the first null.
Rework the string comparison logic to use `memcmp()` for comparing both ucv strings with each other in order to ensure that expressions such as `"" == "\u0000"` lead to the expected `false` result.
Ref: https://github.com/openwrt/luci/issues/6530
=> types: improve comparison reliability of binary strings

lib/rtnl.c
IFLA_IF_NETNSID allows RTM_GETLINK et. al. to operate in other network namespaces. For example I use it to check if a given interface exists in a given namespace.
```js
let reply = rtnl.request(rtnl.const.RTM_GETLINK, rtnl.const.NLM_F_REQUEST, {
"ifname": ifname,
"if_netnsid": nsid,
});
```
The nsid is set with `ip netns set <nsname> <nsid>` and obtained with `ip -j netns list-id`.
=> rtnl: add IFLA_IF_NETNSID for operating in other namespaces

include/ucode/platform.h, lib/uloop.c
Two compile error fixes for macOS, and a fix for preserving the double type when generating JSON.
=> Misc fixes

docs/ucode.css, docs/ucode.js, lib.c, lib/debug.c, lib/fs.c, lib/uci.c
- docs: use CSS and local JavaScript fixups to improve formatting
- uci: add module documentation
- lib: various documentation fixes
=> Various documentation improvements

compiler.c, include/ucode/lexer.h, lexer.c, tests/custom/99_bugs/44_compiler_as_from_identifier
ECMAScript allows using `as` and `from` as identifiers so follow suit and don't treat them specially while parsing. Extend the compiler logic instead to check for TK_LABEL tokens with the expected value to properly parse import and export statements.
=> syntax: don't treat `as` and `from` as reserved keywords

lib/rtnl.c
* rtnl: increase event socket rx buffer size limit to 1 MiB
* rtnl: optimize reception of rtnl events
* rtnl: store callback in listener registry only on success
Fixes: #184
=> rtnl: improve event reception in order to avoid ENOBUFS

include/ucode/types.h, include/ucode/util.h, tests/custom/02_runtime/08_object_iteration, types.c, vm.c
Ensure that deleting object keys during iteration is safe by keeping a global chain of per-object iterators which are advanced to the next key when the entry that is about to be iterated is deleted.
=> vm: rework object iteration

lib/uci.c
When invoked with an explicit package name argument, retain the autoloaded configuration within the context state.
Fixes: #188
=> uci: refactor uci.changes() to match documentation

lib/ubus.c, lib/uci.c, lib/uloop.c
Make all functions clear the last error information on success in order to ensure that `error()` never reports stale information.
=> ubus: automatically clear error information

lib/ubus.c
This is needed when asynchronously processing requests via uloop, e.g. using uclient.
=> ubus: add explicit support for deferring incoming requests

CMakeLists.txt, lib/ubus.c
When uloop has been integrated with eloop (in hostapd/wpa_supplicant), uloop_cancelling will return false, since uloop_run is not being called. This leads to ubus.defer() calling uloop_run in a context where it can prevent the other event loop from running.
Fix this by detecting event loop integration via uloop_fd_set_cb being set
=> ubus: fix uc_ubus_have_uloop for eloop+uloop combination

lib/socket.c
If a non-string value which cannot be interpreted as socket address structure is passed to connect(), the function will leak the internal address vector when returning the error.
=> socket: fix potential memory leak in connect()

lib/socket.c
Optimize the poll() function implementation to re-use passed in socket/flag tuple arrays as-is in the return value array, which simplifies attaching state to sockets for user code through subsequent fields in the tuple array.
=> socket: optimize poll() argument handling

lib/fs.c, tests/custom/03_stdlib/40_proto
Implement flock() and ftruncate()
=> Add fs module utility functions

lib/nl80211.c
For newly added attributes, the kernel prefers to no longer add a nesting
container attribute. Instead, an attribute with the element type is simply
added multiple times within the outer container.
Add support for this array style, which will be used in the pending wiphy
multi radio support.
=> nl80211: add support for multi-attribute arrays

include/linux/nl80211.h, lib/nl80211.c
Support new attributes that describe multiple radios belonging to a single wiphy.
=> nl80211: add wiphy multi-radio support

lib/fs.c, tests/custom/03_stdlib/40_proto
This adds an ioctl method to file, allowing to perform arbitrary ioctl operations on the opened file handle. The caller is responsible for providing correct input to the ioctl operation and is also responsible for packing/unpacking the payload accordingly. 
I'd like to collect some feedback on this, and discuss my implementation attempt. This is the first time I'm dealing with ucode, so probably I missed something here. 
My intention for this is to use it in a written-in-ucode daemon for OpenWrt, but it may be quite useful for other applications too. I hope there aren't any critical objections against having ioctl() support in ucode. 
So far, I only tested a simple ioctl read operation, which works fine. If my proposed changes here are likely to be included, I will test the other …
=> fs: add ioctl() file method

lib/fs.c
Make sure to free the line buffer pointer when aborting a `getline()` / `getdelim()` based read operation on i/o errors.
As an example, this issue could be triggered by receiving a broken pipe error while attempting to read a line from stdin.
=> fs: fix potential memory leak on i/o errors in .read()

compiler.c, tests/custom/99_bugs/47_compiler_no_prop_kw_after_spread
Ensure that unquoted property names following spread expressions in object declaration literals are not treated as keywords.
Prior to this fix, an expression such as `{ ...someobj, default: 1 }` would result in a compile time syntax error.
=> compiler: properly treat property names after spread expressions

tests/custom/99_bugs/49_trailing_garbage_string_as_number, vallist.c
When converting numeric strings into numbers, ensure that only optional trailing whitespace follows and no other characters.
Fixes: #231
=> vallist: more thoroughly check for trailing garbage after numeric string

include/ucode/types.h, tests/custom/99_bugs/48_use_after_free_on_iteration_insert, types.c, vm.c
When keys are added to the object currently being iterated by a for loop, the insert operation might cause a hashtable resize with a subsequent memory reallocation and a different table base pointer, clobbering the entry pointers held by iterators pointing to the containing object of the resized table.
In order to address this issue while keeping the iteration overhead low, extend the object key insert logic to check whether the insertion will trigger a reallocation and backup and restore the iterator pointers when needed.
This slightly increases the size of the iterator states but the overhead for this should be neglectible as there'll only be a low amount of concurrently active iterations at any time.
Fixes: #230
=> types: fix potential use after free on adding keys during iteration

lib/socket.c
The `fanout_args` structure is a relatively recent addition to the kernel so provide a local definition for it, like we already do it for other like `timeval_old`.
Fixes: #217
=> socket: provide local definition of `struct fanout_args`

lib/math.c
The `srand_called` is stored in a registry entry.
=> lib: Removed global variables from module math for thread safety

include/linux/nl80211.h, lib/nl80211.c
- vif radio mask: used to assign vifs to specific radios
- monitor skip_tx flag: do not pass locally transmitted packets on the monitor interface
- radio antenna mask: radio specific part of the phy antenna mask
Support for these attributes has been merged in wireless-next
=> nl80211: add new attributes for multi-radio support

include/ucode/types.h, lib/fs.c
The resource objects are created by resource name, and the last_error is stored in a registry entry.
=> lib: Removed global variables from module fs for thread safety

lib/nl80211.c
When performing a `NL80211_CMD_GET_WIPHY` request for a single wiphy with `split_wiphy_dump` set to true, the expectation is that only a single phy object is returned, like when performing the same request without splitting, yet the current implementation returns a sparse array with only the requested phy index populated instead.
Fix this issue by special-casing NL80211_CMD_GET_WIPHY command requests with a set `split_wiphy_dump` attribute. Also implicitly set the `NLM_F_DUMP` flag in this case as it is required for the kernel to send all information.
=> nl80211: properly support split_wiphy_dump for single phys

main.c
When outputting non-string expression results while running the cli interpreter using the `-p` flag, pretty-print the resulting JSON data for better readability.
=> main: pretty-print `-p` output by default

lib/struct.c
Implement a new struct buffer API to support incremental packing and unpacking of binary data. This API allows for more flexible and efficient handling of structured data, especially for streaming or partial processing scenarios.
=> struct: Add new buffer API for incremental packing/unpacking

main.c
Delete a duplicate ucv_put() line that can lead to a double-free bug.
Reproduced by running:
ucode -l nl80211 -p 'sprintf("%.J\n",
nl80211.request(nl80211.const.NL80211_CMD_GET_WIPHY,
nl80211.const.NLM_F_DUMP,
{ wiphy: 0, split_wiphy_dump: true }))'
Fixes: 0a7ff4715cb8 ("main: pretty-print `-p` output by default")
=> main: fix crash on printing -p output

lib/struct.c
Do not increase the refcount when returning the pulled buffer contents as string since the returned value already is the sole reference. Without this change, pulled buffer contents will be leaked whenever the `pull()` function is used.
Also ensure that the buffer memory is completely zero initialized when it is allocated from scratch, the existing logic only cleared the trailing data area on reallocations but never the head on fresh allocations.
=> struct: fix memory leak in buffer.pull()

debian/control, debian/source/format
Without this a build is failed on the Launchpad CI for PPA.
With the cmake the package was built and available here
https://code.launchpad.net/~stokito/+archive/ubuntu/openwrt
CC @aparcar
=> debian/control: Build-Depend on cmake

debian/control
When installing the ucode with apt it doesn't install the ucode-modules by default.
I added it as a `Recommends:` dependency. Now it will be installed by default but you still can skip it.
[Declaring relationships between packages](https://www.debian.org/doc/debian-policy/ch-relationships.html)
=> debian/control: libucode Recommends ucode-modules

docs/README.md
Fixes: #265 "macOS build broken not finding libucode.0.dylib"
Suggested-by: Felix Fietkau <nbd@nbd.name>
=> docs: Fix compilation command for macOS

lib/socket.c
- Do not unconditionally pass the `MSG_CMSG_CLOEXEC` flag to `recvmsg()` invocations as not all protocol specific recvmsg implementations in the kernel tolerate it; `packet_recvmsg()` for example will immediately return yield `EINVAL` if any non-whitelisted flag is passed.
- Ensure that the HW address string buffer is zero-terminated when converting MAC addresses from C to ucode values.
=> socket: fix AF_PACKET recvmsg() and sockaddr formatting

lib/socket.c
The SO_ATTACH_FILTER socket option requires special handling as it is not passing a self-contained structure to the kernel but a pointer to user memory holding the actual BPF bytecode.
In order to properly support this, first rework the ucode value to C struct conversion callback machinery to pass an indirect struct base pointer, allowing conversion callbacks to realloc the struct memory as needed.
Finally introduce custom uv to C conversion for the BPF data which accepts either a raw bytecode string, an array of opcode arrays or a flat array of opcode values which are converted into a C array of struct sock_filter records appended to the reallocated struct memory.
Attaching a BPF program equivalent to the tcpdump expression `vlan 20 && ether proto 0x1234` would then look like this: …
=> socket: properly support SO_ATTACH_FILTER sockopt

.gitignore, debian/changelog, debian/control, debian/copyright, debian/lintian-overrides
I used the debuild to build a package and it additionally runs lintian checks. Here are fixes of a few of them.
These two remains unfixed:
E: libucode: arch-dependent-file-not-in-arch-specific-directory [usr/lib/libucode.so.20220322]
W: libucode: package-name-doesnt-match-sonames libucode20220322
There is also an error that man pages are missing but I disabled it in the lintian-overrides file.
=> debian: fix lintian warnings

CMakeLists.txt, lib/ubus.c
Improve support for deferring and handling deferred requests
- allow sending and receiving multiple reply messages
- allow sending requests without waiting for a response
- add defer support for channels
- fix broken defer() API footgun
=> ubus deferred request enhancements

lib/ubus.c
Rearrange uc_ubus_defer() in order to lookup the object ID before using it.
Fixes #288
=> ubus: fix broken uc_ubus_defer()

lib/fs.c
Implements fileno() on directory handles and allows using them as chdir() argument.
This allows switching between directories via persistent references.
=> Support for chdir() on opendir() handles

CMakeLists.txt
A naive CFLAGS check is not enough to detect whether some level of source fortification is enabled as the toolchain might use some implicit defaults.
Do a compile time check and test the defined preprocessor directives in order to check for pre-enabled _FORTIFY_SOURCE.
Fixes: #285
=> build: detect whether toolchain employs default source fortification

lib/socket.c
Align the behavior of this function with others and clear the current error information upon returning successfully.
Reported-by: @pony1k
=> socker: let sock.peercred() clear error on success

lib/ubus.c
- Fix clobbering unrelated connections on channel disconnect
- fix use-after-free when using `reply()` on a deferred request
=> Fixes for ubus binding issues

lib/rtnl.c
Do not create temporary string copy if input value already is a string and pass it as-is instead which avoids unnecessary copies and fixes passing binary data payload to netlink.
=> rtnl: optimize string attribute encoding

lib/socket.c
Fix incorrect length when constructing ucode hardware address strings from kernel received address values.
=> socket: fix convertion of hw addresses to ucode strings
